/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-08-24 14:40:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class incorrectpassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html >\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Pure CSS Blurred Video Background Login Box. (fork)</title>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/videologin.css\">\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write(" <body>\r\n");
      out.write("<form action=\"CheckPW\" method=\"post\">\r\n");
      out.write(" <p align=center>\r\n");
      out.write("</p>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"vid-container\">\r\n");
      out.write("\r\n");
      out.write("  <video id=\"Video1\" class=\"bgvid back\" autoplay=\"false\" muted=\"muted\" preload=\"auto\" loop>\r\n");
      out.write("   \r\n");
      out.write("   <source src=\"video/video.mp4\" type=\"video/mp4\">\r\n");
      out.write(" \r\n");
      out.write(" </video>\r\n");
      out.write("  <div class=\"inner-container\">\r\n");
      out.write("    <video id=\"Video2\" class=\"bgvid inner\" autoplay=\"false\" muted=\"muted\" preload=\"auto\" loop>\r\n");
      out.write("   \r\n");
      out.write("   <source src=\"http://shortcodelic1.manuelmasiacsasi.netdna-cdn.com/themes/geode/wp-content/uploads/2014/04/milky-way-river-1280hd.mp4.mp4\" type=\"video/mp4\">\r\n");
      out.write("  \r\n");
      out.write("  </video>\r\n");
      out.write("    <div class=\"box\">\r\n");
      out.write("    \r\n");
      out.write("  <h1>Login</h1>\r\n");
      out.write("    \r\n");
      out.write("  <input type=\"text\" placeholder=\"User Id\" name=\"acid\" />\r\n");
      out.write("   \r\n");
      out.write("   <input type=\"password\" placeholder=\"Password\" name=\"pp\"/>\r\n");
      out.write("    \r\n");
      out.write("  <button>Login</button>\r\n");
      out.write("   <p class=\"message\" align=\"center\"><h3><font color=\"Crimson\">Your ID or Password is Incorrect ! Retype !</font></h3></p>\r\n");
      out.write(" \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write(" <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("     <script src=\"js/index.js\"></script> \r\n");
      out.write("     </form>   \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
