/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-08-24 18:17:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=iso-8859-1\" />\r\n");
      out.write("<title>Menu</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function show() {\r\n");
      out.write("    document.getElementById(\"loading\").style.display=\"block\";\r\n");
      out.write("    setTimeout(\"hide()\", 1000);  // 5 seconds\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function hide() {\r\n");
      out.write("    document.getElementById(\"loading\").style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function valid(){\r\n");
      out.write("\tvar uid1=document.MyForm.uid.value;\r\n");
      out.write("\tvar code1=document.MyForm.code.value;\r\n");
      out.write("\t\tif(uid1==null || uid1==\"\"){\r\n");
      out.write("\t\talert(\"Account ID can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(code1==null || code1==\"\"){\r\n");
      out.write("\t\talert(\"Password can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(typeof code1==='string'){\r\n");
      out.write("\t\talert(\"gsrh\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction isString(value){\r\n");
      out.write("\t\treturn typeof value==='string';\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validform(){\r\n");
      out.write("\tvar id1=document.MyForm.id.value;\r\n");
      out.write("\tvar amount1=document.MyForm.amount.value;\r\n");
      out.write("\t\tif(id1==null || id1==\"\"){\r\n");
      out.write("\t\talert(\"Account ID can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(amount1==null || amount1==\"\"){\r\n");
      out.write("\t\talert(\"Password can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body bgcolor='#373837'>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("  <div id=\"body_image\">&nbsp;</div>\r\n");
      out.write("  <div id=\"page_header\">\r\n");
      out.write("    <h1><span>Menu</span></h1>\r\n");
      out.write("    <h3><span>Welcome Admin</span></h3>\r\n");
      out.write("    <div class=\"clearthis\">&nbsp;</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"page_menu\">\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li class=\"online\"><a href=\"admintable.jsp\"><span>Admin info</span></a><span></span></li>\r\n");
      out.write("      <li class=\"downloads\"><a href=\"usertable.jsp\"><span>user info</span></a><span></span></li>\r\n");
      out.write("      <li class=\"community\"><a href=history.jsp><span>deposit</span></a><span></span></li>\r\n");
      out.write("      <li class=\"about\"><a href=\"vdologin.jsp\"><span>history</span></a><span></span></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"page_forms\">\r\n");
      out.write("    <div id=\"userlogin\">\r\n");
      out.write("      <div id=\"userlogin_header\">\r\n");
      out.write("        <h2><span>User </span></h2>\r\n");
      out.write("      </div>\r\n");
      out.write("      <form name=\"MyForm\" action=\"test\" method=\"post\" onsubmit=\"return validform()\">\r\n");
      out.write("        <div id=\"field_username\" > <strong><span>Log :</span></strong>\r\n");
      out.write("          <input type=\"text\" name=\"id\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"field_password\" > <strong><span>Password:</span></strong>\r\n");
      out.write("          <input type=\"text\" name=\"amount\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"button_enter\">\r\n");
      out.write("          <input type=\"image\" src=\"img/sitesearch_button.gif\" alt=\"Enter\"  class=\"button\" />\r\n");
      out.write("        </div></div>\r\n");
      out.write("      </form>\r\n");
      out.write("       <div id=\"page_forms\">\r\n");
      out.write("    <div id=\"userlogin\">\r\n");
      out.write("      <div id=\"userlogin_header2\">\r\n");
      out.write("        <h2><span>User </span></h2>\r\n");
      out.write("      </div>\r\n");
      out.write("      <form action=\"testjavawd\" method=\"post\" name=\"Myform\" onsubmit=\"return valid()\" >\r\n");
      out.write("        <div id=\"field_username\" > <strong><span>Log :</span></strong>\r\n");
      out.write("          <input type=\"text\" name=\"uid\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"field_code\" > <strong><span>Password:</span></strong>\r\n");
      out.write("          <input type=\"text\" name=\"code\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"button_enter\">\r\n");
      out.write("          <input type=\"image\" src=\"img/sitesearch_button.gif\" alt=\"Enter\"   class=\"button\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clearthis\">&nbsp;</div>\r\n");
      out.write("      </form>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"content_body\">\r\n");
      out.write("    <div id=\"reviews_box\">\r\n");
      out.write("      <div id=\"reviews\">\r\n");
      out.write("        <div class=\"content_header\">\r\n");
      out.write("          <h2><span>Recent Reviews</span></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content_entry\">\r\n");
      out.write("          <div class=\"thumbnail\"><img src=\"img/_image04.jpg\" width=\"121\" height=\"90\" alt=\"Image Caption\" /></div>\r\n");
      out.write("          <div class=\"entry_text\">\r\n");
      out.write("            <p>The web application \"Easy Money\" offer the fastest cash transfer. It can available at over 40 towns in Myanmar with the lowest service charge.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clearthis\">&nbsp;</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content_entry\">\r\n");
      out.write("          <div class=\"thumbnail\"><img src=\"img/_image02.jpg\" width=\"118\" height=\"88\" alt=\"Image Caption\" /></div>\r\n");
      out.write("          <div class=\"entry_text\">\r\n");
      out.write("            <p>You can enjoy a very convenient way of earning in \"Easy Money\",too.Hold in charge of an agent in \"Easy Money\" in your home or shop with a very sweet salary without any disturbance to your profession!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clearthis\">&nbsp;</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"playnow_box\">\r\n");
      out.write("      <div id=\"playnow\">\r\n");
      out.write("        <div class=\"content_header\">\r\n");
      out.write("          <h2><span>Play Now</span></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content_entry\">\r\n");
      out.write("          <div class=\"thumbnail\"><img src=\"img/_image03.jpg\" width=\"118\" height=\"88\" alt=\"Image Caption\" /></div>\r\n");
      out.write("          <div class=\"entry_text\">\r\n");
      out.write("                      <p>Contact the nearest agent and submit a CV form to work as an agent! If you cannot find that,email to <u>hnineiwinkyaw56@gmail.com</u>. Otherwise, call to hotline <u>+959798692413!</u> </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clearthis\">&nbsp;</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content_entry\">\r\n");
      out.write("          <div class=\"thumbnail\"><img src=\"img/_image01.jpg\" width=\"118\" height=\"88\" alt=\"Image Caption\" /></div>\r\n");
      out.write("          <div class=\"entry_text\">\r\n");
      out.write("           \r\n");
      out.write("            <p>Now, \"Easy Money\" is used in increasing number of clients! So, thanks a lot to our agents for delivering us to our clients! You can enjoy extra bonus and higher positions at the end of every year! Join us and make your opportunities! Warmly welcome our agents!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clearthis\">&nbsp;</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"clearthis_contentbody\">&nbsp;</div>\r\n");
      out.write("   <center>   <div id=\"page_footer\"> Copyright www.yoursite.com | designed by <u>4IS-A J2EE project group-8</u> </div></center>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write(" </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
