/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-08-24 17:24:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserLoginFail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html >\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("    <title>Login/Logout animation concept</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=yes\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Open+Sans'>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validform(){\r\n");
      out.write("var id=document.MyForm.acc.value;\r\n");
      out.write("var psw=document.MyForm.pass.value;\r\n");
      out.write("if(id==null || id==\"\"){\r\n");
      out.write("\talert(\"Account ID can't be blank!\");\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("else if(psw==null || psw==\"\"){\r\n");
      out.write("\talert(\"Password can't be blank!\");\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validform1(){\r\n");
      out.write("\tvar fn=document.myForm.fname.value;\r\n");
      out.write("\tvar ln=document.myForm.lname.value;\r\n");
      out.write("\tvar pn=document.myForm.phno.value;\r\n");
      out.write("\tvar ad=document.myForm.address.value;\r\n");
      out.write("\tvar gd=document.myForm.gender.value;\r\n");
      out.write("\tvar id=document.myForm.accid.value;\r\n");
      out.write("\tvar psw=document.myForm.pass.value;\r\n");
      out.write("\tvar cpsw=document.myForm.cpass.value;\r\n");
      out.write("\tif(fn==null || fn==\"\" || fn.length<1){\r\n");
      out.write("\t\talert(\"First name can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(ln==null || ln==\"\" || ln==\" \" || ln.length<1){\r\n");
      out.write("\t\talert(\"Last name can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(pn==null || pn==\"\" || pn==\" \" || pn.length<1){\r\n");
      out.write("\t\talert(\"Phone number can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(ad==null || ad==\"\" || ad==\" \" || ad.length<1){\r\n");
      out.write("\t\talert(\"Address can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(gd==null || gd==\"\" || gd==\" \" || gd.length<1){\r\n");
      out.write("\t\talert(\"Gender can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(gd==null || gd==\"\"){\r\n");
      out.write("\t\talert(\"Gender must be selected!!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(id==null || id==\"\" || id==\" \" || id.length<1){\r\n");
      out.write("\t\talert(\"Account ID can't be blank!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(psw==null || psw==\"\" || psw==\" \" || psw.length<6){\r\n");
      out.write("\t\talert(\"Password can't be blank and must be at least 6 character!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(cpsw==null || cpsw==\"\" || cpsw==\" \" || cpsw.length<6){\r\n");
      out.write("\t\talert(\"Confirm password can't be blank and must be at least 6 character!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"cont\">\r\n");
      out.write("  <div class=\"demo\">\r\n");
      out.write("    <div class=\"login\"> \r\n");
      out.write("    ");

         session=request.getSession();
      	 String sms=(String)session.getAttribute("msg");
      	 if(sms=="aaa"){ 
      out.write("\r\n");
      out.write("      \t <font size=5 color=\"red\"><pre>    Incorrect Account!</pre></font>\r\n");
      out.write("      \t");
 
      	 }
      	 else if(sms=="bbb"){ 
      out.write("\r\n");
      out.write("      \t <font size=5 color=\"red\"><pre>    Incorrect Password!</pre></font>\r\n");
      out.write("       \t");
 
      		 
      	 }
      	 
      out.write("\r\n");
      out.write("      <div class=\"login__check\"></div>\r\n");
      out.write("      <div class=\"login__form\">\r\n");
      out.write("<form name=\"MyForm\" action=\"MyLogin\" method=\"post\" onsubmit=\"return validform()\">\r\n");
      out.write("         <div class=\"login__row\">\r\n");
      out.write("           <svg class=\"login__icon name svg-icon\" viewBox=\"0 0 20 20\">\r\n");
      out.write("            <path d=\"M0,20 a10,8 0 0,1 20,0z M10,0 a4,4 0 0,1 0,8 a4,4 0 0,1 0,-8\" />\r\n");
      out.write("          </svg>\r\n");
      out.write("           <input type=\"text\" class=\"app_top__input name\" name=\"acc\" placeholder=\"Account ID\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"login__row\">\r\n");
      out.write("           <svg class=\"login__icon pass svg-icon\" viewBox=\"0 0 20 20\">\r\n");
      out.write("            <path d=\"M0,20 20,20 20,8 0,8z M10,13 10,16z M4,8 a6,8 0 0,1 12,0\" />\r\n");
      out.write("          </svg>\r\n");
      out.write("           <input type=\"password\" class=\"app_top__input name\" name=\"pass\" placeholder=\"Password\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("         <input type=\"submit\" class=\"signup__submit\" value=\"Log in\"/><br>\r\n");
      out.write("</form>    \r\n");
      out.write("        <p class=\"login__signup\"><a href=\"signup.jsp\">Don't have an account? &nbsp;</a><br>\r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"js/index.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
